### ISSUE TITLE
Wrong URL

### ISSUE THREAD

**Issue by mozzieongit** [mozzieongit/step2019team08-WebProjekt#1]
In Branch front:
file: webcontent/cgi-bin/view_data.sh
line 51 (wrong path)
\-  gplot="../html/img/plot_test.svg"
\+ gplot="../img/plot_test.svg"

**Comment by muradr777** [comment]
ok, thanks

**Comment by muradr777** [comment]
Solved. 
[https://github.com/mozzieongit/step2019team08-WebProjekt/commit/74e52ad9d3922e45f227132e4450d878289231b9](Link to Commit)
